name: Publish Release

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  buildRelease: # Job
    name: Build Release APK
    runs-on: ubuntu-latest # The type of runner that the job will run on   
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repo
        uses: actions/checkout@v2
        
      - name: Set up JDK enviroment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Setup Python enviroment
              uses: actions/setup-python@v2
              with:
                python-version: 3.8.5
          
      - name: Build app
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: assembleRelease
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          gradle-version: current

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Move APK
        run: |
          mkdir ./github_release
          cp ${{ env.SIGNED_RELEASE_FILE }} ~/github_release/

      - name: Create apk env info entries, move APK
        run: |
          python .github/build_scripts/extract_info.py
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: NovelDokusha v${{ env.APP_RELEASE_VERSION }}
          tag_name: ${{ env.APP_RELEASE_VERSION }}
          files: |
            ${{ env.APP_RELEASE_FILE }}
          
        
